export const LOAD_COMIC_INIT = 'LOAD_COMIC/INIT';
export const LOAD_COMIC_SUCCESS = 'LOAD_COMIC/SUCCESS';
export const LOAD_COMIC_ERROR = 'LOAD_COMIC/ERROR';

export const SET_LATEST_COMIC_ID = 'SET_LATEST_COMIC_ID';

export const SEARCH_COMIC_INIT = 'SEARCH_COMIC/INIT';